spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: daniel
    password: Tencent520..
    url: jdbc:mysql://localhost:3306/drug_cart_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true&allowPublicKeyRetrieval=true
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 10
      read-only: false
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.daniel.cart.domain

server:
  port: 8989
  servlet:
    context-path: /


